# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
print(np.version.version)
print(np.show_config())

1.20.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


#### 3. Create a null vector of size 10 (★☆☆)

In [13]:
A = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [14]:
A.size*A.itemsize

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-5-1663cd30cb7c>, line 1)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
A[4] = 1
print(A)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [17]:
B = np.arange(10,50)
print(B)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [19]:
BI = B[::-1]
print(BI)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
np.array([[0,1,2],[3,4,5],[6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [25]:
C = np.nonzero([1,2,0,0,4,0])
print(C)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [27]:
np.random.random((3,3,3))

array([[[0.42342468, 0.1343286 , 0.4619986 ],
        [0.48827811, 0.83771272, 0.78344567],
        [0.47259621, 0.39621949, 0.29345454]],

       [[0.58401788, 0.35798167, 0.5527808 ],
        [0.70862464, 0.80241484, 0.45392591],
        [0.2128897 , 0.48079909, 0.46674009]],

       [[0.95207039, 0.89673178, 0.84931318],
        [0.02804196, 0.01687297, 0.56654274],
        [0.46520564, 0.3610605 , 0.90238002]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [30]:
D = np.random.random((10,10))
print(D)
print(D.max(),D.min())

[[0.7464655  0.95468662 0.45394686 0.51676462 0.02036426 0.22091933
  0.9694639  0.70076982 0.93040482 0.75763575]
 [0.1960609  0.00250385 0.61065068 0.21389891 0.94516888 0.02832403
  0.1477443  0.61668152 0.0649016  0.30345485]
 [0.9577053  0.86295552 0.49068821 0.47510889 0.96729124 0.5986836
  0.01287217 0.16147752 0.81749408 0.78704887]
 [0.53231168 0.330853   0.40872465 0.92025967 0.44246847 0.81459816
  0.13227391 0.81471327 0.9438741  0.66426603]
 [0.93418687 0.66111418 0.5359235  0.78464396 0.28995866 0.15673251
  0.37139568 0.83719587 0.94903222 0.64439952]
 [0.26062066 0.7058691  0.14464249 0.72115128 0.11830625 0.07029964
  0.8326051  0.80245882 0.09395649 0.39758965]
 [0.73398367 0.04998253 0.83182456 0.06362045 0.64082863 0.56592217
  0.34682397 0.31734567 0.544398   0.32593042]
 [0.12232085 0.62254363 0.19651654 0.55090107 0.38557364 0.23385365
  0.40038679 0.48469748 0.38059887 0.08255459]
 [0.69212482 0.37546421 0.73792796 0.02552931 0.36569793 0.91699341
  0.3518651  

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [32]:
E = np.random.random(10)
print(E)
print(E.mean())

[0.74564177 0.54417155 0.93185118 0.81264486 0.03368274 0.32514231
 0.49168889 0.07860766 0.09580703 0.9160923 ]
0.4975330297423898


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [33]:
F = np.ones((3,3))
F[1:-1,1:-1] = 0
print(F)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [35]:
G = np.pad(F, pad_width=1, mode='constant', constant_values=0)
print(G)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [37]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [10]:
H = np.diag(1+np.arange(4),k=-1)
print(H)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [16]:
I = np.zeros((8, 8), dtype = int)
I[1::2, ::2] = 1
I[::2, 1::2] = 1
print(I)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [17]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [30]:
arr = np.array([[0,1],[1,0]])
repetitions = (4, 4)
np.tile(arr, repetitions)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [34]:
J = np.random.random((5,5))
print(J)
J = (J - J.min())/(J.max() - J.min())
print(J)

[[0.33504239 0.66979791 0.18381476 0.36304133 0.60306169]
 [0.87317234 0.781377   0.9778799  0.91051358 0.43246125]
 [0.02076211 0.57205239 0.35935374 0.4793086  0.94647715]
 [0.38090754 0.78988695 0.59958495 0.67331202 0.88094802]
 [0.90419459 0.24573238 0.32704191 0.73125248 0.37953206]]
[[0.32836113 0.67811486 0.17035798 0.35761452 0.60838863]
 [0.89060118 0.79469309 1.         0.92961543 0.43014469]
 [0.         0.57599    0.35376172 0.47909097 0.96719029]
 [0.3762812  0.80358431 0.60475612 0.68178642 0.89872523]
 [0.92301333 0.23504973 0.32000221 0.74232281 0.3748441 ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [35]:
K = np.random.random((5,3))
L = np.random.random((3,2))
M = np.dot(K,L)
print(M)

[[0.44078436 0.57672914]
 [0.56224872 0.82390816]
 [0.71485311 0.86962315]
 [1.06113489 1.39275264]
 [0.96121602 1.34845704]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [51]:
N = np.arange(11)
N = np.delete(N, np.argwhere( (N >= 3) & (N <= 8)))
print(N)

[ 0  1  2  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [53]:
print(np.sum(range(5),-1))
from numpy import *
print(np.sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [64]:
Z = np.arange(2)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[0 1]
[1 1]
[0 1]
[False False]
[0.+0.j 0.+1.j]
[0. 1.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [65]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-65-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-65-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [72]:
O = np.random.uniform(0,10,10)
print(O)
P = np.round(O,0)
print(P)


[2.94457009 0.12669236 2.54118777 6.87382302 9.06477291 8.02017549
 5.54161872 5.10573058 3.37657406 4.54050191]
[3. 0. 3. 7. 9. 8. 6. 5. 3. 5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [75]:
Q = np.random.randint(0,10,10)
R = np.random.randint(0,10,10)
print(np.intersect1d(Q,R))

[2 4 6 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [77]:
np.seterr(all="ignore")
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [41]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
  
print(yesterday,today,tomorrow)

2021-09-08 2021-09-09 2021-09-10


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [78]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [83]:
print(np.tile(np.arange(0, 5), (5,1)))

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

Generator(PCG64)


AttributeError: 'numpy.random._generator.Generator' object has no attribute 'a'

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [91]:
print(np.linspace(0,1,11,endpoint=False)[1:])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [92]:
S = np.arange(10)
np.add.reduce(S)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [95]:
T = np.random.randint(0,10,5)
U = np.random.randint(0,10,5)
print(T)
print(U)
print(np.array_equal(T,U))

[2 3 3 8 4]
[1 2 8 7 0]
False


#### 43. Make an array immutable (read-only) (★★☆)

In [99]:
I = np.random.random(10)
I[I.argmax()] = 0
print(I)

[0.926554   0.         0.37922956 0.74398588 0.4128342  0.51809874
 0.3133041  0.73175022 0.86755883 0.0212737 ]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [97]:
V = np.random.random((10,2))
W,X = V[:,0], V[:,1]
Y = np.sqrt(X**2+Y**2)
Z = np.arctan2(Y,X)
print(Y)
print(Z)

[0.88947071 0.29879327 0.52121166 0.5137305  0.28174844 0.11070192
 0.89680114 0.82192652 1.02343094 0.91543514]
[0.78731376 1.0024449  0.87406934 1.45620079 1.49245966 0.96399334
 1.54794837 0.86520353 0.83140372 1.20981288]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [100]:
Z1 = np.random.random(10)
Z1[Z1.argmax()] = 0
print(Z1)

[0.47955826 0.73691408 0.84049068 0.60482146 0.50649531 0.74295028
 0.62614938 0.         0.71586497 0.32622507]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [101]:
Z2 = np.zeros((10,10), [('x',float),('y',float)])
Z2['x'], Z2['y'] = np.meshgrid(np.linspace(0,1,10), np.linspace(0,1,10))
print(Z2)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
np.set_printoptions(threshold=np.nan)
A1 = np.zeros((7,7))
print(A1)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [102]:
B1 = np.arange(100)
C1 = np.random.uniform(0,100)
index = (np.abs(B1-C1)).argmin()
print(B1[index])

39


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [105]:
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11 ''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

NameError: name 'StringIO' is not defined

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

False


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)